### ISSUE TITLE
ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by Qweua** [tolwi/hassio-ecoflow-cloud#48]
After updating HA to 2023.5.0/2023.5.1 have problem with integration:

Logger: homeassistant.config_entries
Source: custom_components/ecoflow-cloud/__init__.py:65
Integration: EcoFlow-Cloud (documentation, issues)
First occurred: 9:54:46 PM (1 occurrences)
Last logged: 9:54:46 PM

Error setting up entry 263 for ecoflow-cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ecoflow-cloud/__init__.py", line 65, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, _PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

Any recommendations?

Thanks

**Comment by neotigger** [comment]
https://github.com/vwt12eh8/hassio-ecoflow/pull/79/commits/c0ff2b42844f44a0062e89c8f5f8d04ac446429f

**Comment by tolwi** [comment]
looks like you have an outdated version (`ecoflow-cloud` became `ecoflow_cloud` in v0.5.0) - manually remove custom_components/ecoflow-cloud/ folder and reinstall integration.

**Comment by Qweua** [comment]
Helped solution from this link
https://github.com/vwt12eh8/hassio-ecoflow/commit/c0ff2b42844f44a0062e89c8f5f8d04ac446429f
