### ISSUE TITLE
1.1.0-pre4 Error setting up entry Home for ecoflow_cloud

### ISSUE THREAD

**Issue by SBozhyi** [tolwi/hassio-ecoflow-cloud#298]
After updating to 1.1.0-pre4  integration doesn't start up

Error setting up entry Home for ecoflow_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/__init__.py", line 214, in async_setup_entry
    device = api_client.configure_device(device_data.sn, device_data.name, device_data.device_type,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/private_api.py", line 84, in configure_device
    info = self.__create_device_info(device_sn, device_name, device_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ecoflow_cloud/api/private_api.py", line 97, in __create_device_info
    return EcoflowDeviceInfo(
           ^^^^^^^^^^^^^^^^^^
TypeError: EcoflowDeviceInfo.__init__() missing 1 required positional argument: 'status'

**Comment by TrilIiard** [comment]
+1

**Comment by SBozhyi** [comment]
Fixed. Thanks!
